### ISSUE TITLE
PHP error using ui-libraries Scribe and Scripto

### ISSUE THREAD

**Issue by clintonblackmore** [ui-libraries/DIYHistory-transcribe#1]
Greetings.

I hope this is a suitable place to mention this issue.  [I would've done it on the page for Scribe, but there is no issues button there.]  I'm trying to set up a site for transcribing documents for family history purposes, and I must say, it is fabulous you've made the versions of the software available that you are using at DIY History.

I ran into a PHP error with the ui-libraries version of Scribe and Scripto, so I've done a clean setup, and still get the error, "Call to undefined function set_current_item()".

STEPS TO REPRODUCE

In a system with Apache and PHP (in this test, I used MAMP 3.2.1, with Apache 2 and PHP 5.6.7),
- install omeka (2.3.1)
- install and configure https://github.com/ui-libraries/plugin-Scripto and mediawiki 1.26.2
- install https://github.com/ui-libraries/Scribe
- upload an item for transcription

- Leave the omeka admin dashboard and go to the page [see picture 1]
<img width="493" alt="1-clickonfile" src="https://cloud.githubusercontent.com/assets/64144/12396194/67d87384-bdc3-11e5-9fe1-982f10c73e88.png">

- Click on the item in the collection [see picture 2]
<img width="257" alt="2-clicktotranscribe" src="https://cloud.githubusercontent.com/assets/64144/12396195/67de3260-bdc3-11e5-9bdd-4238743fb367.png">

- This should bring up the transcription page, but it is empty, it only shows the site header. [see picture 3].
<img width="479" alt="3-notabletotranscribe" src="https://cloud.githubusercontent.com/assets/64144/12396196/68084d20-bdc3-11e5-935e-969c9c06980a.png">

- The following line is written to the PHP error log when (attempting to) bring up the transcription:

    [18-Jan-2016 17:04:24 Europe/Berlin] PHP Fatal error:  Call to undefined function set_current_item() in /Applications/MAMP/htdocs/omeka/themes/Scribe/scripto/index/transcribe.php on line 325

EXPECTED RESULT

The transcription page should've come up, and worked.  [Note that it does work, (although not very pretty and lacking all the additions made by DIY History), if a use a different theme. See Image 4.]

<img width="484" alt="4-transcriptionworkswithothertheme" src="https://cloud.githubusercontent.com/assets/64144/12396197/6821b44a-bdc3-11e5-9249-6589e2c4cffb.png">

NOTES:

When I installed you're fork of Scripto, and Scribe, I cloned the latest from git. It occurs to me that perhaps I shouldn't use the master branch, or that perhaps I should use a snapshot of files.

I do intend to try other forks of these plugins and themes, but it would be really nice if your branches worked right, for they feel the most official.

Cheers, and Thanks,
Clinton Blackmore

**Comment by mbutler** [comment]
I've pushed a change to the Scribe theme that changes an old function name. Could you pull down the new Scribe and try again? Thanks.

**Comment by clintonblackmore** [comment]
Thank you, mbutler.  

That is significantly better.  It no longer logs errors and the full page loads.

I'm finding it doesn't work with OpenLayers images, though, whereas other themes do.  [It doesn't work with Zoom.it, either, but that doesn't appear to be working under any circumstances for me].  I suppose I should take some more screenshots and write up a new report.

Thank you so much for looking into this.
