### ISSUE TITLE
Unable to zoom in and out on images

### ISSUE THREAD

**Issue by gamecompany** [ui-libraries/DIYHistory-transcribe#2]
Hello again, and sorry to trouble you.

I love the setup on the DIY History site (love the way you can resize the window between the transcription and the image, too -- I don't suppose that theme is available?), and, I also like how you can zoom in and out on the image to transcribe.  

## STEPS TO REPRODUCE

In a system with Apache and PHP (in this test, I used MAMP 3.2.1, with Apache 2 and PHP 5.6.7),

- install omeka (2.3.1)
- install and configure https://github.com/ui-libraries/plugin-Scripto and mediawiki 1.26.2
- install https://github.com/ui-libraries/Scribe
- (I have installed Scribe and Script from git, and did a pull on them both to ensure I was up-to-date with the ui-libraries forks of them.)
- upload an item for transcription, and go to the transcription page for it.
- In the dashboard, try the different options for Image Viewer [Omeka default, OpenLayers, Zoom.it]

Here is what I see.  I am using three different themes (left to right, they are "Berlin", "Scribe", and "Thanks, Roy".)  I have them all open to the same page (http://localhost:8888/omeka/scripto/transcribe/1/1#transcription) to show off the different settings.

### Omeka Default

This actually looks decent on the Scribe theme, for it shows the image.  The other themes show a link which, if clicked, brings up the image (and my Chrome browser will let me zoom to full size on it, and zoom out to fit the whole image in the window, but that's insufficient for the hard-to-read text.)

<img width="2035" alt="screen shot 2016-01-24 at 8 48 47 pm" src="https://cloud.githubusercontent.com/assets/12502391/12542465/cce20020-c2e0-11e5-811a-1dd2b271b5ca.png">

### OpenLayers

I get good/expected results with the themes that are unaware of the ui-libraries enhancements to Scripto, but using the Scribe theme, I just get the file's name -- I can't even click on it to see it.

<img width="2037" alt="screen shot 2016-01-24 at 8 50 24 pm" src="https://cloud.githubusercontent.com/assets/12502391/12542471/d1bdbbac-c2e0-11e5-9e1d-172727402202.png">

### Zoom.it

Zoom.it doesn't work.  As [their website](http://zoom.it/) says they're in transition and not converting new images, this isn't a surprise.

<img width="2029" alt="screen shot 2016-01-24 at 8 51 28 pm" src="https://cloud.githubusercontent.com/assets/12502391/12542472/d6dba7c0-c2e0-11e5-997b-72d0a347334a.png">

## EXPECTED RESULTS

I expect that Scribe (or a similar theme, enhanced to understand the changes to Scripto for knowing if transcription is underway on any file) will provide some way of letting me zoom in and out on images; in particular, I expect OpenLayers to work with it.

## [DESIRED RESULTS]

[This is ridiculously out of scope, and not the appropriate place for it, but man, I'd love an image viewer that would be even more helpful, and if you know of anything trying to do that, I'd love to know about it.  If it could let me adjust contrast, do dynamic thresholding, let me change the scaling mode from bilinear to nearest pixel, that'd be awesome.  One step up from that would be if I could, on the fly, run things like [Fred's Textcleaner](http://www.fmwconcepts.com/imagemagick/textcleaner/) and adjust parameters -- or, really going crazy -- let me reduce JPEG artifacting or even find and vectorize the outlines of the text and display it to me.]

**Comment by mbutler** [comment]
It looks like the CSS file was not being included for some reason. I've restored the funtion and everything should hopefully work now. You can pull down the updated Scribe repo or just look at the latest commit for the one line to add in to your transcribe.php file.

**Comment by gamecompany** [comment]
That worked like a charm.  Thank you so much.
